/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { Migrations } from "./Migrations";
export type { MockDaiToken } from "./MockDaiToken";
export type { TokenFarm } from "./TokenFarm";
export type { YYToken } from "./YYToken";
