/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import type BN from "bn.js";
import type { ContractOptions } from "web3-eth-contract";
import type { EventLog } from "web3-core";
import type { EventEmitter } from "events";
import type {
  Callback,
  PayableTransactionObject,
  NonPayableTransactionObject,
  BlockType,
  ContractEventLog,
  BaseContract,
} from "./types";

export interface EventOptions {
  filter?: object;
  fromBlock?: BlockType;
  topics?: string[];
}

export interface TokenFarm extends BaseContract {
  constructor(
    jsonInterface: any[],
    address?: string,
    options?: ContractOptions
  ): TokenFarm;
  clone(): TokenFarm;
  methods: {
    hasStaked(arg0: string): NonPayableTransactionObject<boolean>;

    isStaking(arg0: string): NonPayableTransactionObject<boolean>;

    mockDaiToken(): NonPayableTransactionObject<string>;

    name(): NonPayableTransactionObject<string>;

    owner(): NonPayableTransactionObject<string>;

    stakers(arg0: number | string | BN): NonPayableTransactionObject<string>;

    stakingBalance(arg0: string): NonPayableTransactionObject<string>;

    yyToken(): NonPayableTransactionObject<string>;

    stakeTokens(
      _amount: number | string | BN
    ): NonPayableTransactionObject<void>;

    issueTokens(): NonPayableTransactionObject<void>;

    unstakeTokens(): NonPayableTransactionObject<void>;
  };
  events: {
    allEvents(options?: EventOptions, cb?: Callback<EventLog>): EventEmitter;
  };
}
